# Project information
docs_dir: doc
site_name: rapiddweller Benerator
site_url: https://docs.benerator.de
site_author: rapiddweller GmbH & Volker Bergmann
copyright: Copyright &copy; 2006 - 2022 rapiddweller GmbH & Volker Bergmann
site_description: >-
  This document is supposed to become a complete summary of everything you need to know of Benerator usage,
  use it efficiently and extend it as you need. This reference is under construction and will update from time to time.
  Feel free to contribute your ideas in our repo at https://github.com/rapiddweller/rapiddweller-benerator-ce/.

# Repository
repo_name: rapiddweller-benerator-ce
repo_url: https://github.com/rapiddweller/rapiddweller-benerator-ce
edit_uri: ""

extra_css:
  - css/extra.css
  - css/termynal.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  - js/termynal.js
  - js/custom.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.js

theme:
  name: material
  logo: assets/rd.png
  favicon: assets/favicon-32x32.png
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: rapiddweller
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top

use_directory_urls: false

plugins:
  - search
  - print-site:
      add_to_navigation: false
      print_page_title: 'rapiddweller Benerator EE'
      add_print_site_banner: true
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Content'
      toc_depth: 1
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: doc
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.snippets
  - tables
  - abbr

# Page tree
nav:
  - Home: index.md
  - Goals and Features: introduction_to_benerator.md
  - Installation: installation.md
  - The Benerator Project Wizard: the_benerator_project_wizard.md
  - Quick tour through the descriptor file format: quick_tour_through_the_descriptor_file_format.md
  - Data Generation Concepts: data_generation_concepts.md
  - Data Anonymization Concepts: data_anonymization_concepts.md
  - Regular Expression Support: regular_expression_support.md
  - CSV File Generation/Anonymization: data_file_processing.md
  - XML File Processing: xml_file_processing.md
  - Distribution Concepts: distribution.md
  - Using Relational Databases: using_relational_databases.md
  - Message Queue Access (Enterprise Edition): message_queue_access.md
  - Kafka Access (Enterprise Edition): kafka_access.md
  - Environment Files: environment_files.md
  - Advanced Topics: advanced_topics.md
  - Generating Unique Data: generating_unique_data.md
  - Scripting: scripting.md
  - rapiddwellerScript: rapiddwellerscript.md
  - Command Line Tools: command_line_tools.md
  - Domains: domains.md
  - Component Reference: component_reference.md
  - No SQL Databases: no_sql_support.md
  - Using DB Sanity: using_db_sanity.md
  - Maven Benerator Plugin: maven_benerator_plugin.md
  - Extending Benerator: extending_benerator.md
  - Using Benerator as Load Generator: using_benerator_as_load_generator.md
  - Troubleshooting: troubleshooting.md
  - Monitoring Benerator: monitoring_benerator.md
  - Benerator Performance Tuning: performance_tuning.md
  - Migrating Benerator Projects: migrating_benerator_projects.md

extra:
  social:
    - icon: fontawesome/brands/square-github
      link: https://github.com/rapiddweller/rapiddweller-benerator-ce
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/rapiddweller
    - icon: fontawesome/brands/square-facebook
      link: https://www.facebook.com/rapiddweller/
    - icon: fontawesome/brands/square-twitter
      link: https://twitter.com/intent/follow?screen_name=rapiddweller
