DROP TABLE IF EXISTS db_order_item CASCADE;
DROP TABLE IF EXISTS db_order CASCADE;
DROP TABLE IF EXISTS db_customer CASCADE;
DROP TABLE IF EXISTS db_user CASCADE;
DROP TABLE IF EXISTS db_role CASCADE;
DROP TABLE IF EXISTS db_product CASCADE;
DROP TABLE IF EXISTS db_category CASCADE;
DROP SEQUENCE IF EXISTS seq_id_gen;
