#bash
if [ -z "$GITHUB_REF" ]; then
  export ARTIFACT_VERSION=$ARTIFACT_VERSION_BASE+$JAVA_JDKVERSION_TAG-SNAPSHOT
else
  export ARTIFACT_VERSION=$GITHUB_REF+$JAVA_JDKVERSION_TAG
fi
export ARTIFACT_FULLNAME=$ARTIFACT_ID-$ARTIFACT_VERSION
