# This is a basic workflow to help you get started with Actions

name: deploy docs

on:
  push:
    branches:
      - development 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install markdown-include
      - run: pip install mkdocs-markdownextradata-plugin
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-with-pdf
      - run: pip install weasyprint
      - run: mkdocs gh-deploy --force
