# This is a basic workflow to help you get started with Actions

name: deploy docs

on:
  push:
    branches:
      - development 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.3.0
      - run: pip install mkdocs-material==8.2.8
      - run: pip install markdown-include==0.6.0
      - run: pip install mkdocs-markdownextradata-plugin==0.2.5
      - run: pip install pymdown-extensions==9.1
      - run: pip install mkdocs-with-pdf==0.9.3
      - run: pip install weasyprint==52.5
      - run: mkdocs gh-deploy --force
